
DIRETORIO_RAIZ = "/tcc"
DIRETORIO_DATASET = "/dataset"
DIRETORIO_DATASET_ORIGINAL = "/35"
CAMINHO_RELATIVO = "/home/eron/Documentos"
CAMINHO_ABSOLUTO_DATASET = CAMINHO_RELATIVO + DIRETORIO_RAIZ + DIRETORIO_DATASET
CAMINHO_ABSOLUTO_DATASET_ORIGINAL = CAMINHO_RELATIVO + DIRETORIO_RAIZ + DIRETORIO_DATASET + DIRETORIO_DATASET_ORIGINAL
